// This file is auto generated by build/build-renderer.js
import MDCode from './MDCode.vue';
import MDMath from './MDMath.vue';
import MDMermaid from './MDMermaid.vue';
import { renderKatex } from './katexManager.js';

// 导出所有渲染器组件
export {
  MDCode,
  MDMath,
  MDMermaid,
  renderKatex
};

// 默认导出包含所有组件的对象
export default {
  MDCode,
  MDMath,
  MDMermaid,
  renderKatex,

  // 安装函数，用于 Vue.use()
  install(app) {
    app.component('mdcode', MDCode);
    app.component('mdmath', MDMath);
    app.component('mdmermaid', MDMermaid);
  },

  version: '3.3.0-beta.12'
};
