// This file is auto generated by build/build-renderer.js
import MDCode from './MDCode.vue';

// font css
import '@/assets/css/font';

const version = '3.4.2';

const install = (app) => {
  app.component(MDCode.name || 'mdcode', MDCode);
};

MDCode.version = version;
MDCode.install = install;

MDCode.use = function (optionsOrInstall, opt) {
  if (typeof optionsOrInstall === 'function') {
    optionsOrInstall(MDCode, opt);
  } else {
    optionsOrInstall.install(MDCode, opt);
  }

  return MDCode;
};

export default MDCode;
