// This file is auto generated by build/build-renderer.js
import MDMath from './MDMath.vue';

// font css

const version = '3.3.0-beta.12';

const install = (app) => {
  app.component(MDMath.name || 'mdmath', MDMath);
};

MDMath.version = version;
MDMath.install = install;

MDMath.use = function (optionsOrInstall, opt) {
  if (typeof optionsOrInstall === 'function') {
    optionsOrInstall(MDMath, opt);
  } else {
    optionsOrInstall.install(MDMath, opt);
  }

  return MDMath;
};

export default MDMath;
