// This file is auto generated by build/build-renderer.js
import MDMermaid from './MDMermaid.vue';

// font css
import '@/assets/css/font';

const version = '3.4.1-beta.0';

const install = (app) => {
  app.component(MDMermaid.name || 'mdmermaid', MDMermaid);
};

MDMermaid.version = version;
MDMermaid.install = install;

MDMermaid.use = function (optionsOrInstall, opt) {
  if (typeof optionsOrInstall === 'function') {
    optionsOrInstall(MDMermaid, opt);
  } else {
    optionsOrInstall.install(MDMermaid, opt);
  }

  return MDMermaid;
};

export default MDMermaid;
